name: Laravel

on:

  push:

    branches: [ "main" ]

    paths: 
      - 'app/**'
      - 'bootstrap/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      - 'storage/**'
      - 'tests/**'
      - 'composer.*'
      - '!**.md'

  pull_request:

  workflow_dispatch:

jobs:

  format-code-style:

    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    
    - name: Format with Laravel Pint
      uses: aglipanci/laravel-pint-action@2.4
      with:
        onlyDirty: true
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Format code style
    
  run-tests:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup PHP
      uses: shivammathur/setup-php@2.30.1
      with:
        php-version: '8.1'
        extensions: curl, exif, fileinfo, gd, intl, mbstring, mysqli, openssl, pdo_mysql, pdo_sqlite, sqlite3, xsl
      
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests
      run: ./vendor/bin/phpunit
